In [245]:
import numpy as np


In [246]:
def generate2(M):
    for v in len(M):
        
        a = list(range(0,p)) + list(range(p+1, V))
        rnds = np.random.choice(a, 2, replace = False)
        rt1 = str(p) + " " + str(rnds[0]) + " " + str(round(np.random.uniform(0,1),3)) + "\n"
        rt2 = str(p) + " " + str(rnds[1]) + " " + str(round(np.random.uniform(0,1),3)) + "\n"
    return rt1+rt2
    
def create_graph(V):
    M = np.zeros((V,V))
    data = str(V)+"\n"
    for v in range(V):
        indxs = np.where(M[v] != 1)
        msk = np.random.choice(indxs[0], int(0.85*len(M[v])), replace = False)
        M[v][msk] = 1
    
    utl = np.tril_indices(V, -1)
    M[utl] = 0
    checker = {}
    uti = np.tril_indices(V, 1)
    for row in range( V):
        for col in range(row+1, V):
            if M[row][col] : 
                M[col][row] = 1
                
                checker[col] = checker [col] + 1 if col in checker else 1
                checker[row] = checker [row] + 1 if row in checker else 1
                weight = np.random.uniform(0, 100)
                data += str(row)+ " "+ str(col) + " " + str(round(weight, 2)) + "\n"
                
    for x in range(V):
        if x not in checker or checker[x] < 2 :
            return None, None
            
    return M, data

In [247]:
file1 = open("30.in", "w+")
data = create_graph(30)[1]
file1.write(data)
file1.close()

file1 = open("50.in", "w+")
data = create_graph(50)[1]
file1.write(data)
file1.close()

file1 = open("100.in", "w+")
data = create_graph(100)[1]
file1.write(data)
file1.close()

In [244]:
def generate_rnd_edges(n, portion):
   
    # upper triangular indicies with diagonal offset 1 (diagonal elements are not included)
    iu1 = np.triu_indices(n, 1)
    
    # choose randomly number of portion of the possible edges
    msk = np.random.choice(len(iu1[0]), int(portion*len(iu1[0])), replace = False)
    
    
    masked = (iu1[0][msk], iu1[1][msk])
    a = np.zeros((10,10))
    a[masked] = 1
    indicies = np.where(a>0)
    print(a)
    return list(zip(indicies[0],indicies[1]))


In [155]:
b  = generate_rnd_edges(10, 0.8)


[[0. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 1. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
